# Generated by Django 3.1 on 2020-10-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201022_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='countries',
            field=models.ManyToManyField(related_name='movies', to='core.Country'),
        ),
    ]
