# Generated by Django 3.1 on 2020-10-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201022_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='age_limit',
            field=models.IntegerField(blank=True, choices=[(0, 'kids'), (1, 'teens'), (2, 'adults')], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('title', 'released')},
        ),
    ]
